name: Build Android AAB
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Esta acción oficial descarga todo lo necesario y compila
      - name: Build AAB with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: :app:bundleDebug
 
